chore(ci): add merge group for checks and enhance test result validation

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -6,6 +6,8 @@ on:
     branches: ["master"]
   pull_request:
     branches: ["master"]
+  merge_group:
+    types: [checks_requested]
 
 permissions:
     contents: read
@@ -37,3 +39,17 @@ jobs:
 
       - name: "Enforce coverage"
         run: uv run coverage report --show-missing --skip-covered --fail-under=100
+
+  check-tests:
+    name: "Tests successful"
+    needs: [tests]
+    runs-on: "ubuntu-latest"
+    if: always()
+
+    steps:
+      - name: "Check results"
+        run: |
+          if [ "${{ needs.tests.result }}" != "success" ]; then
+            echo "Tests failed"
+            exit 1
+          fi
